FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    default-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/default-java
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY consumer/ ./consumer/
COPY .env.example .
CMD ["python", "consumer/spark_consumer.py"]